# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ns3-wormsim', ['ns3-worm', 'core'])
    obj.source = 'ns3-wormsim.cc'
